-- ═══════════════════════════════════════════════════════════════
-- SYSTEMFORGE AI — COMPLETE DATA PIPELINE SCHEMA
-- 13 tables · 5 agents · Full pipeline coverage
-- Run in Supabase SQL Editor in order: Block 1 → Block 6
-- ═══════════════════════════════════════════════════════════════

-- ═══ BLOCK 1: SHARED FOUNDATION TABLES ═══════════════════════

-- Master lead record — created the moment anyone interacts with any agent
CREATE TABLE leads (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now(),
  session_id      TEXT,
  name            TEXT,
  email           TEXT,
  phone           TEXT,
  business_type   TEXT,
  business_name   TEXT,
  lead_source     TEXT DEFAULT 'chat',        -- dm / walk-in / organic / referral / ad / chat
  intent_score    INTEGER DEFAULT 5 CHECK (intent_score BETWEEN 1 AND 10),
  status          TEXT DEFAULT 'new',          -- new / warm / hot / converted / lost
  last_agent      TEXT DEFAULT 'forge',        -- forge / scout / builder / guard / closer
  converted       BOOLEAN DEFAULT false,
  converted_at    TIMESTAMPTZ,
  notes           TEXT
);

-- One record per chat window opened on any page
CREATE TABLE chat_sessions (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at      TIMESTAMPTZ DEFAULT now(),
  session_id      TEXT UNIQUE NOT NULL,
  lead_id         UUID REFERENCES leads(id),
  current_agent   TEXT DEFAULT 'forge',
  agents_visited  TEXT[] DEFAULT '{forge}',
  source_url      TEXT,
  referrer        TEXT,
  device_type     TEXT,                        -- mobile / desktop / tablet
  total_messages  INTEGER DEFAULT 0,
  duration_seconds INTEGER,
  ended_at        TIMESTAMPTZ
);

-- Every time an agent routes a visitor to another agent
CREATE TABLE agent_handoffs (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at      TIMESTAMPTZ DEFAULT now(),
  session_id      TEXT REFERENCES chat_sessions(session_id),
  lead_id         UUID REFERENCES leads(id),
  from_agent      TEXT NOT NULL,               -- forge / scout / builder / guard / closer
  to_agent        TEXT NOT NULL,
  reason          TEXT,                        -- why the handoff was triggered
  trigger_message TEXT                         -- the message that caused the route
);

-- Lightweight event log for page views, CTA clicks, audit starts
CREATE TABLE page_events (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at      TIMESTAMPTZ DEFAULT now(),
  session_id      TEXT,
  event_type      TEXT NOT NULL,               -- page_view / cta_click / audit_start / report_shown / chat_open
  page            TEXT,
  detail          TEXT,
  lead_id         UUID REFERENCES leads(id)
);


-- ═══ BLOCK 1b: HOMEPAGE AUDIT LEADS ══════════════════════════
CREATE TABLE audit_leads (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at          TIMESTAMPTZ DEFAULT now(),
  session_id          TEXT,
  business_type       TEXT,
  leak_amount         TEXT,
  missing_systems     TEXT[],
  recommended_fixes   TEXT[],
  messages            JSONB DEFAULT '[]',
  report_shown        BOOLEAN DEFAULT false,
  cta_clicked         BOOLEAN DEFAULT false,
  converted           BOOLEAN DEFAULT false,
  email               TEXT,
  name                TEXT,
  phone               TEXT,
  source_page         TEXT DEFAULT 'homepage'
);
ALTER TABLE audit_leads ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_audit_leads_session ON audit_leads(session_id);
CREATE INDEX idx_audit_leads_converted ON audit_leads(converted);

-- ═══ BLOCK 2: FORGE + SCOUT AGENT TABLES ══════════════════════

-- Full conversation log for every Forge (sales qualifier) session
CREATE TABLE forge_conversations (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at      TIMESTAMPTZ DEFAULT now(),
  session_id      TEXT REFERENCES chat_sessions(session_id),
  lead_id         UUID REFERENCES leads(id),
  messages        JSONB DEFAULT '[]',          -- [{role, content, timestamp}]
  business_type   TEXT,                        -- extracted from conversation
  visitor_intent  TEXT,                        -- audit / pricing / support / info / browse
  routed_to       TEXT,                        -- which agent they were sent to
  routed_at       TIMESTAMPTZ,
  source_url      TEXT,
  referrer        TEXT
);

-- One record per audit session initiated by Scout
CREATE TABLE audit_sessions (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at      TIMESTAMPTZ DEFAULT now(),
  session_id      TEXT REFERENCES chat_sessions(session_id),
  lead_id         UUID REFERENCES leads(id),
  started_at      TIMESTAMPTZ DEFAULT now(),
  completed_at    TIMESTAMPTZ,
  questions_asked INTEGER DEFAULT 0,
  source_agent    TEXT DEFAULT 'forge'         -- which agent handed off to Scout
);

-- Full audit output — generated by Scout after Q&A sequence
CREATE TABLE audit_reports (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at          TIMESTAMPTZ DEFAULT now(),
  session_id          TEXT REFERENCES chat_sessions(session_id),
  lead_id             UUID REFERENCES leads(id),
  audit_session_id    UUID REFERENCES audit_sessions(id),
  business_type       TEXT,
  business_name       TEXT,
  q_and_a             JSONB DEFAULT '[]',      -- [{question, answer}] all 7 pairs
  full_conversation   JSONB DEFAULT '[]',      -- complete scout conversation
  identified_gaps     TEXT[],                  -- array of gap descriptions
  revenue_leak_low    INTEGER,                 -- monthly low estimate in dollars
  revenue_leak_high   INTEGER,                 -- monthly high estimate in dollars
  recommended_tier    INTEGER CHECK (recommended_tier IN (1,2,3)),
  report_shown        BOOLEAN DEFAULT false,
  cta_clicked         BOOLEAN DEFAULT false,
  converted           BOOLEAN DEFAULT false,
  converted_at        TIMESTAMPTZ,
  converted_tier      INTEGER
);


-- ═══ BLOCK 3: BUILDER AGENT TABLES ════════════════════════════

-- Chat conversations between Builder agent and paying clients
CREATE TABLE builder_conversations (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at      TIMESTAMPTZ DEFAULT now(),
  session_id      TEXT REFERENCES chat_sessions(session_id),
  client_id       UUID REFERENCES paid_clients(id),
  messages        JSONB DEFAULT '[]',
  topic           TEXT,                        -- status / intake / support / handoff / training
  resolved        BOOLEAN DEFAULT false,
  escalated_to_guard BOOLEAN DEFAULT false
);

-- Every status change on a client build — full audit trail
CREATE TABLE build_status_log (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at          TIMESTAMPTZ DEFAULT now(),
  client_id           UUID REFERENCES paid_clients(id),
  status_from         TEXT,                    -- previous status
  status_to           TEXT NOT NULL,           -- new / in_progress / review / delivered / complete
  changed_at          TIMESTAMPTZ DEFAULT now(),
  changed_by          TEXT DEFAULT 'system',   -- owner / builder_agent / system / client
  delivery_deadline   TIMESTAMPTZ,             -- SLA deadline based on tier
  delivered_at        TIMESTAMPTZ,             -- actual delivery time
  on_time             BOOLEAN,                 -- was it within SLA?
  loom_url            TEXT,                    -- walkthrough video link
  handoff_call_url    TEXT,                    -- Calendly booking link
  notes               TEXT
);

-- Post-delivery satisfaction captured by Builder agent
CREATE TABLE client_satisfaction (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at          TIMESTAMPTZ DEFAULT now(),
  client_id           UUID REFERENCES paid_clients(id),
  score               INTEGER CHECK (score BETWEEN 1 AND 5),
  testimonial         TEXT,
  permission_to_share BOOLEAN DEFAULT false,
  survey_source       TEXT DEFAULT 'builder_chat',
  follow_up_needed    BOOLEAN DEFAULT false
);


-- ═══ BLOCK 4: GUARD AGENT TABLES ══════════════════════════════

-- Every support issue raised through the Guard agent
CREATE TABLE support_tickets (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now(),
  session_id      TEXT REFERENCES chat_sessions(session_id),
  client_id       UUID REFERENCES paid_clients(id),  -- nullable — non-clients can raise issues
  lead_id         UUID REFERENCES leads(id),           -- if they haven't purchased
  issue_type      TEXT NOT NULL,               -- refund / late_delivery / billing / quality / other
  severity        TEXT DEFAULT 'medium',       -- low / medium / high / critical
  description     TEXT,                        -- client's exact words from chat
  conversation    JSONB DEFAULT '[]',          -- full guard conversation
  status          TEXT DEFAULT 'open',         -- open / in_review / resolved / escalated / closed
  resolution      TEXT,                        -- refund / redo / resolved / escalated / dismissed
  resolution_notes TEXT,
  resolved_at     TIMESTAMPTZ,
  owner_notified  BOOLEAN DEFAULT false,
  owner_notified_at TIMESTAMPTZ,
  refund_id       UUID                         -- FK added after refund_log created
);

-- Financial record of every refund processed
CREATE TABLE refund_log (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at          TIMESTAMPTZ DEFAULT now(),
  client_id           UUID REFERENCES paid_clients(id),
  ticket_id           UUID REFERENCES support_tickets(id),
  stripe_refund_id    TEXT,                    -- from Stripe API
  original_charge_id  TEXT,                    -- original Stripe payment intent ID
  amount_cents        INTEGER NOT NULL,         -- amount refunded in cents
  reason              TEXT,                    -- late_delivery / not_as_described / client_request
  refund_type         TEXT DEFAULT 'full',     -- full / partial
  processed_at        TIMESTAMPTZ,
  processed_by        TEXT DEFAULT 'owner'
);


-- ═══ BLOCK 5: CLOSER AGENT TABLES ═════════════════════════════

-- Warm leads flagged for Closer agent recovery
CREATE TABLE closer_leads (
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at          TIMESTAMPTZ DEFAULT now(),
  lead_id             UUID REFERENCES leads(id),
  audit_report_id     UUID REFERENCES audit_reports(id),
  flagged_at          TIMESTAMPTZ DEFAULT now(),
  flag_reason         TEXT DEFAULT 'audit_no_purchase',  -- audit_no_purchase / cart_abandoned / re_engagement
  times_contacted     INTEGER DEFAULT 0,
  re_engaged          BOOLEAN DEFAULT false,
  re_engaged_at       TIMESTAMPTZ,
  last_contact_at     TIMESTAMPTZ,
  next_contact_date   DATE
);

-- Full outcome record for every Closer recovery conversation
CREATE TABLE closer_outcomes (
  id                    UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at            TIMESTAMPTZ DEFAULT now(),
  lead_id               UUID REFERENCES leads(id),
  audit_report_id       UUID REFERENCES audit_reports(id),
  session_id            TEXT REFERENCES chat_sessions(session_id),
  objection_type        TEXT,                  -- price / timing / trust / unsure / competitive
  objection_text        TEXT,                  -- their exact words
  response_given        TEXT,                  -- what Closer said
  conversation          JSONB DEFAULT '[]',    -- full closer exchange
  outcome               TEXT DEFAULT 'pending', -- won / lost / nurture / no_response / pending
  outcome_notes         TEXT,
  follow_up_date        DATE,
  converted_to_client   BOOLEAN DEFAULT false,
  converted_at          TIMESTAMPTZ,
  converted_tier        INTEGER,
  revenue_recovered     INTEGER                -- amount of the eventual purchase in cents
);


-- ═══ BLOCK 6: SECURITY, INDEXES + TRIGGERS ════════════════════

-- Enable Row Level Security on all tables
ALTER TABLE leads                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_sessions           ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_handoffs          ENABLE ROW LEVEL SECURITY;
ALTER TABLE page_events             ENABLE ROW LEVEL SECURITY;
ALTER TABLE forge_conversations     ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_sessions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_reports           ENABLE ROW LEVEL SECURITY;
ALTER TABLE builder_conversations   ENABLE ROW LEVEL SECURITY;
ALTER TABLE build_status_log        ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_satisfaction     ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_tickets         ENABLE ROW LEVEL SECURITY;
ALTER TABLE refund_log              ENABLE ROW LEVEL SECURITY;
ALTER TABLE closer_leads            ENABLE ROW LEVEL SECURITY;
ALTER TABLE closer_outcomes         ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (chat widget writes data from the browser)
DO $$ DECLARE t TEXT;
BEGIN FOR t IN SELECT tablename FROM pg_tables WHERE schemaname='public'
  LOOP EXECUTE format(
    'CREATE POLICY "anon_insert_%s" ON %I FOR INSERT TO anon WITH CHECK (true)', t, t
  );
END LOOP; END $$;

-- Auto-update updated_at on leads and support_tickets
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER leads_updated_at
  BEFORE UPDATE ON leads
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER tickets_updated_at
  BEFORE UPDATE ON support_tickets
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Auto-flag leads for Closer when audit completes without purchase
CREATE OR REPLACE FUNCTION flag_unconverted_audit()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.report_shown = true AND NEW.converted = false THEN
    INSERT INTO closer_leads (lead_id, audit_report_id, flag_reason)
    VALUES (NEW.lead_id, NEW.id, 'audit_no_purchase')
    ON CONFLICT DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER auto_flag_closer_lead
  AFTER UPDATE ON audit_reports
  FOR EACH ROW
  WHEN (OLD.report_shown IS DISTINCT FROM NEW.report_shown)
  EXECUTE FUNCTION flag_unconverted_audit();

-- Performance indexes
CREATE INDEX idx_leads_session       ON leads(session_id);
CREATE INDEX idx_leads_status        ON leads(status);
CREATE INDEX idx_leads_converted     ON leads(converted);
CREATE INDEX idx_leads_business_type ON leads(business_type);
CREATE INDEX idx_chat_session_id     ON chat_sessions(session_id);
CREATE INDEX idx_audit_lead          ON audit_reports(lead_id);
CREATE INDEX idx_audit_converted     ON audit_reports(converted);
CREATE INDEX idx_audit_tier          ON audit_reports(recommended_tier);
CREATE INDEX idx_tickets_status      ON support_tickets(status);
CREATE INDEX idx_tickets_severity    ON support_tickets(severity);
CREATE INDEX idx_closer_outcome      ON closer_outcomes(outcome);
CREATE INDEX idx_closer_converted    ON closer_outcomes(converted_to_client);
CREATE INDEX idx_build_client        ON build_status_log(client_id);
CREATE INDEX idx_build_status        ON build_status_log(status_to);
CREATE INDEX idx_handoffs_session    ON agent_handoffs(session_id);
CREATE INDEX idx_page_events_type    ON page_events(event_type);

-- ═══════════════════════════════════════════════════════════════
-- VERIFICATION QUERY — run this after all blocks complete
-- Should return 14 rows (one per table)
-- ═══════════════════════════════════════════════════════════════
SELECT tablename, 
       (SELECT COUNT(*) FROM information_schema.columns 
        WHERE table_name = tablename AND table_schema = 'public') AS column_count
FROM pg_tables 
WHERE schemaname = 'public' 
ORDER BY tablename;
